version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-api
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9229:9229"
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - crm-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm-network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - crm-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025" # Porta SMTP
      - "8025:8025" # Interface web
    networks:
      - crm-network

volumes:
  postgres_data:

networks:
  crm-network:
    driver: bridge